package main

// cmd_missions_attachments.go — `hirebots missions attachments` commands to
// list, download (raw encrypted), and decrypt mission attachments.

import (
	"archive/zip"
	"bytes"
	"crypto/aes"
	"crypto/cipher"
	"crypto/ed25519"
	"crypto/sha512"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"golang.org/x/crypto/blake2b"
	"golang.org/x/crypto/curve25519"
	"golang.org/x/crypto/nacl/box"

	"github.com/spf13/cobra"
)

var missionsAttachmentsCmd = &cobra.Command{
	Use:   "attachments",
	Short: "List, download, and decrypt attachments for a mission",
}

var missionsAttachmentsListCmd = &cobra.Command{
	Use:   "list <mission-id>",
	Short: "List attachments for a specific mission",
	Args:  cobra.ExactArgs(1),
	RunE:  runMissionsAttachmentsList,
}

var missionsAttachmentsDownloadCmd = &cobra.Command{
	Use:   "download <mission-id> <attachment-id>",
	Short: "Download a single attachment (raw encrypted bytes saved as .enc)",
	Args:  cobra.ExactArgs(2),
	RunE:  runMissionsAttachmentsDownload,
}

var missionsAttachmentsDecryptCmd = &cobra.Command{
	Use:   "decrypt <mission-id> <attachment-id>",
	Short: "Download and decrypt an attachment using the bot's Ed25519 private key",
	Args:  cobra.ExactArgs(2),
	RunE:  runMissionsAttachmentsDecrypt,
}

func init() {
	missionsAttachmentsCmd.AddCommand(missionsAttachmentsListCmd)
	missionsAttachmentsCmd.AddCommand(missionsAttachmentsDownloadCmd)
	missionsAttachmentsCmd.AddCommand(missionsAttachmentsDecryptCmd)
	// --key-file on decrypt lets the bot specify an alternative Ed25519
	// private key file (e.g. PKCS#8 PEM generated by other tools). If not
	// set, loadPrivateKey() defaults to ~/.hirebots/ed25519.pem.
	missionsAttachmentsDecryptCmd.Flags().StringVar(&regKeyFile, "key-file", "", "Ed25519 private key file (PEM). Defaults to ~/.hirebots/ed25519.pem.")
	missionsCmd.AddCommand(missionsAttachmentsCmd)
}

// attachment mirrors the JSON shape returned by GET /missions/{id}/attachments.
type attachment struct {
	ID             string `json:"id"`
	MissionID      string `json:"mission_id"`
	Filename       string `json:"filename"`
	FileSizeBytes  int64  `json:"file_size_bytes"`
	SHA256Hash     string `json:"sha256_hash"`
	Description    string `json:"description"`
	EncryptionType string `json:"encryption_type"`
	UploadedAt     string `json:"uploaded_at"`
}

// downloadResponse mirrors the JSON returned by GET /missions/{id}/attachments/{id}/download.
// The backend now returns this JSON envelope instead of raw octet-stream bytes.
type downloadResponse struct {
	EncryptedFileB64  string `json:"encrypted_file_b64"`
	EncryptedKeyB64   string `json:"encrypted_key_b64"`
	Filename          string `json:"filename"`
	FileSizeBytes     int64  `json:"file_size_bytes"`
	CompressionType   string `json:"compression_type"`
	EncryptionType    string `json:"encryption_type"`
}

func runMissionsAttachmentsList(cmd *cobra.Command, args []string) error {
	client := newClient(apiURL, apiToken)
	missionID := args[0]

	body, err := client.get("/missions/" + missionID + "/attachments")
	if err != nil {
		return fmt.Errorf("fetching attachments: %w", err)
	}

	var resp struct {
		Items []attachment `json:"items"`
		Total int          `json:"total"`
	}
	if err := jsonUnmarshal(body, &resp); err != nil {
		return fmt.Errorf("parsing attachments response: %w", err)
	}

	if len(resp.Items) == 0 {
		fmt.Println("No attachments found for this mission.")
		return nil
	}

	fmt.Printf("%-38s  %-24s  %-10s  %-10s  %s\n", "ID", "FILENAME", "SIZE", "ENCRYPTED", "UPLOADED")
	fmt.Println(strings.Repeat("-", 100))
	for _, a := range resp.Items {
		encrypted := "no"
		if strings.ToLower(a.EncryptionType) != "none" && a.EncryptionType != "" {
			encrypted = "yes"
		}
		fmt.Printf("%-38s  %-24s  %-10s  %-10s  %s\n",
			a.ID,
			truncate(a.Filename, 24),
			humanSize(a.FileSizeBytes),
			encrypted,
			formatDate(a.UploadedAt),
		)
	}
	fmt.Printf("\nTotal: %d\n", resp.Total)
	return nil
}

// fetchDownloadJSON fetches the download endpoint and parses the JSON envelope.
func fetchDownloadJSON(client *Client, missionID, attachmentID string) (*downloadResponse, error) {
	body, err := client.get("/missions/" + missionID + "/attachments/" + attachmentID + "/download")
	if err != nil {
		return nil, fmt.Errorf("downloading attachment: %w", err)
	}
	var dl downloadResponse
	if err := json.Unmarshal(body, &dl); err != nil {
		return nil, fmt.Errorf("parsing download response JSON: %w", err)
	}
	return &dl, nil
}

func runMissionsAttachmentsDownload(cmd *cobra.Command, args []string) error {
	client := newClient(apiURL, apiToken)
	missionID := args[0]
	attachmentID := args[1]

	dl, err := fetchDownloadJSON(client, missionID, attachmentID)
	if err != nil {
		return err
	}

	// Decode the base64-encoded encrypted file blob.
	encData, err := base64.StdEncoding.DecodeString(dl.EncryptedFileB64)
	if err != nil {
		return fmt.Errorf("decoding encrypted_file_b64: %w", err)
	}

	// Save the raw encrypted bytes to a .enc file using the original filename.
	outName := sanitizeFilename(dl.Filename)
	if outName == "" || outName == "attachment.bin" {
		outName = "attachment_" + shortID(attachmentID, 8) + ".enc"
	} else {
		// Append .enc to the original filename.
		outName = outName + ".enc"
	}

	if err := os.WriteFile(outName, encData, 0600); err != nil {
		return fmt.Errorf("writing encrypted file: %w", err)
	}

	fmt.Printf("Saved %d encrypted bytes to %s\n", len(encData), outName)
	if dl.EncryptedKeyB64 != "" {
		fmt.Printf("  (encrypted AES key: %d b64 chars)\n", len(dl.EncryptedKeyB64))
	}
	return nil
}

func runMissionsAttachmentsDecrypt(cmd *cobra.Command, args []string) error {
	client := newClient(apiURL, apiToken)
	missionID := args[0]
	attachmentID := args[1]

	dl, err := fetchDownloadJSON(client, missionID, attachmentID)
	if err != nil {
		return err
	}

	// Step 1: Load the bot's Ed25519 private key.
	privKey, err := loadPrivateKey()
	if err != nil {
		return err
	}

	// Step 2: Recover the AES key.
	// For 'hybrid' attachments, the AES key is X25519-wrapped (SealedBox).
	// For 'aes_only' attachments, the AES key is plaintext (use directly).
	encKeyB64 := dl.EncryptedKeyB64
	if encKeyB64 == "" {
		return fmt.Errorf("download response has no encrypted_key_b64 — cannot decrypt")
	}
	encKey, err := base64.StdEncoding.DecodeString(encKeyB64)
	if err != nil {
		return fmt.Errorf("decoding encrypted_key_b64: %w", err)
	}

	var aesKey []byte
	switch strings.ToLower(dl.EncryptionType) {
	case "hybrid", "x25519_sealed", "":
		// X25519 SealedBox wrapped AES key — decrypt with the bot's Ed25519 private key.
		aesKey, err = sealedBoxOpen(encKey, privKey)
		if err != nil {
			return fmt.Errorf("decrypting AES key (SealedBox): %w", err)
		}
	case "aes_only":
		// Plaintext AES key — use directly without SealedBox.
		aesKey = encKey
	default:
		return fmt.Errorf("unsupported encryption_type: %q", dl.EncryptionType)
	}

	if len(aesKey) != 32 {
		return fmt.Errorf("recovered AES key is %d bytes (expected 32)", len(aesKey))
	}

	// Step 3: Decrypt the file via AES-256-GCM.
	encFileB64 := dl.EncryptedFileB64
	if encFileB64 == "" {
		return fmt.Errorf("download response has no encrypted_file_b64 — cannot decrypt")
	}
	encData, err := base64.StdEncoding.DecodeString(encFileB64)
	if err != nil {
		return fmt.Errorf("decoding encrypted_file_b64: %w", err)
	}
	plaintext, err := aesGCMDecrypt(encData, aesKey)
	if err != nil {
		return fmt.Errorf("decrypting file (AES-256-GCM): %w", err)
	}

	// Step 4: Decompress ZIP if compression_type == "zip".
	var finalData []byte
	switch strings.ToLower(dl.CompressionType) {
	case "zip":
		finalData, err = zipDecompress(plaintext)
		if err != nil {
			return fmt.Errorf("decompressing ZIP: %w", err)
		}
		fmt.Printf("✓ Decompressed ZIP (%d → %d bytes)\n", len(plaintext), len(finalData))
	case "none", "":
		finalData = plaintext
	default:
		return fmt.Errorf("unsupported compression_type: %s", dl.CompressionType)
	}

	// Step 5: Write the decrypted file to disk with the original filename.
	outName := sanitizeFilename(dl.Filename)
	if outName == "" || outName == "attachment.bin" {
		outName = "attachment_" + shortID(attachmentID, 8) + ".bin"
	}

	if err := os.WriteFile(outName, finalData, 0600); err != nil {
		return fmt.Errorf("writing decrypted file: %w", err)
	}

	fmt.Printf("✓ Decrypted and saved %d bytes to %s\n", len(finalData), outName)
	return nil
}

// sealedBoxOpen decrypts a PyNaCl SealedBox ciphertext using the recipient's
// Ed25519 private key (converted to X25519).
//
// SealedBox format (PyNaCl/libsodium crypto_box_seal):
// [32 bytes ephemeral_pub] + [crypto_box ciphertext]
//
// crypto_box_seal internally uses crypto_box_easy, which is:
//   1. nonce = blake2b-24(ephemeral_pub || recipient_pub)
//   2. shared = X25519(ephemeral_sk, recipient_pub)
//   3. derived_key = HSalsa20(nonce[:16], shared)
//   4. ciphertext = secretbox(msg, nonce[16:], derived_key)
//
// Therefore we must use box.Open (which does HSalsa20 + secretbox),
// NOT secretbox.Open directly — the raw X25519 shared secret is NOT
// the secretbox key.
func sealedBoxOpen(sealed []byte, edPriv ed25519.PrivateKey) ([]byte, error) {
	if len(sealed) < 32+box.Overhead {
		return nil, fmt.Errorf("sealed box too short: %d bytes", len(sealed))
	}

	// Extract the ephemeral public key (first 32 bytes) and the ciphertext.
	ephemeralPub := sealed[:32]
	ciphertext := sealed[32:]

	// Convert the Ed25519 private key to an X25519 private key.
	// PyNaCl's crypto_sign_ed25519_sk_to_curve25519 takes the 64-byte Ed25519
	// secret key, hashes the 32-byte seed with SHA-512, and clamps the first
	// 32 bytes per RFC 8032 to produce the X25519 private key.
	if len(edPriv) != ed25519.PrivateKeySize {
		return nil, fmt.Errorf("invalid Ed25519 private key size: %d (expected %d)", len(edPriv), ed25519.PrivateKeySize)
	}
	seed := edPriv[:32] // First 32 bytes of the Ed25519 private key is the seed.
	h := sha512.Sum512(seed)
	x25519Priv := h[:32]
	// Clamp per RFC 8032 / curve25519:
	x25519Priv[0] &= 248
	x25519Priv[31] &= 127
	x25519Priv[31] |= 64

	// Derive the X25519 public key from the X25519 private key.
	// This matches PyNaCl's crypto_sign_ed25519_pk_to_curve25519.
	x25519Pub, err := curve25519.X25519(x25519Priv, curve25519.Basepoint)
	if err != nil {
		return nil, fmt.Errorf("deriving X25519 public key: %w", err)
	}

	// Compute the nonce: blake2b-24(ephemeral_pub || recipient_pub).
	// PyNaCl/libsodium uses Blake2b with a 24-byte output size.
	h2, err := blake2b.New(24, nil)
	if err != nil {
		return nil, fmt.Errorf("creating blake2b hasher: %w", err)
	}
	h2.Write(ephemeralPub)
	h2.Write(x25519Pub)
	var nonce [24]byte
	copy(nonce[:], h2.Sum(nil))

	// Use box.Open to decrypt — this does HSalsa20 key derivation + secretbox
	// internally, matching how libsodium's crypto_box_seal produced the ciphertext.
	var peerPub [32]byte
	copy(peerPub[:], ephemeralPub)
	var privKey [32]byte
	copy(privKey[:], x25519Priv)

	plaintext, ok := box.Open(nil, ciphertext, &nonce, &peerPub, &privKey)
	if !ok {
		return nil, fmt.Errorf("box.Open failed — invalid ciphertext or wrong key")
	}
	return plaintext, nil
}

// aesGCMDecrypt decrypts AES-256-GCM ciphertext where the first 12 bytes are
// the nonce and the remainder is the encrypted data + GCM tag.
func aesGCMDecrypt(ciphertext, key []byte) ([]byte, error) {
	if len(ciphertext) < 12+16 {
		return nil, fmt.Errorf("ciphertext too short: %d bytes (need at least 28)", len(ciphertext))
	}

	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, fmt.Errorf("creating AES cipher: %w", err)
	}

	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, fmt.Errorf("creating GCM: %w", err)
	}

	nonce := ciphertext[:12]
	encrypted := ciphertext[12:]

	plaintext, err := gcm.Open(nil, nonce, encrypted, nil)
	if err != nil {
		return nil, fmt.Errorf("AES-GCM decrypt failed: %w", err)
	}
	return plaintext, nil
}

// zipDecompress decompresses a ZIP archive in memory and returns the
// concatenated contents of all files. If the archive contains a single file,
// only that file's contents are returned.
func zipDecompress(data []byte) ([]byte, error) {
	r, err := zip.NewReader(bytes.NewReader(data), int64(len(data)))
	if err != nil {
		return nil, fmt.Errorf("opening zip reader: %w", err)
	}

	// If there's a single file, return its contents directly.
	if len(r.File) == 1 {
		f := r.File[0]
		rc, err := f.Open()
		if err != nil {
			return nil, fmt.Errorf("opening zip entry %s: %w", f.Name, err)
		}
		defer rc.Close()
		return io.ReadAll(rc)
	}

	// Multiple files: concatenate all file contents.
	var buf bytes.Buffer
	for _, f := range r.File {
		rc, err := f.Open()
		if err != nil {
			return nil, fmt.Errorf("opening zip entry %s: %w", f.Name, err)
		}
		_, err = io.Copy(&buf, rc)
		rc.Close()
		if err != nil {
			return nil, fmt.Errorf("reading zip entry %s: %w", f.Name, err)
		}
	}
	return buf.Bytes(), nil
}

// sanitizeFilename strips path separators and resolves to a basename.
func sanitizeFilename(name string) string {
	name = filepath.Base(name)
	if name == "." || name == "/" || name == "" {
		return "attachment.bin"
	}
	return name
}

// shortID returns the first n characters of an ID (UUID).
func shortID(id string, n int) string {
	if len(id) <= n {
		return id
	}
	return id[:n]
}

// truncate shortens s to maxLen, appending "…" if truncated.
func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-1] + "…"
}

// humanSize renders a byte count as a human-readable KB/MB/GB string.
func humanSize(n int64) string {
	const (
		KB = 1024
		MB = 1024 * KB
		GB = 1024 * MB
	)
	switch {
	case n >= GB:
		return fmt.Sprintf("%.2f GB", float64(n)/float64(GB))
	case n >= MB:
		return fmt.Sprintf("%.2f MB", float64(n)/float64(MB))
	case n >= KB:
		return fmt.Sprintf("%.1f KB", float64(n)/float64(KB))
	default:
		return fmt.Sprintf("%d B", n)
	}
}

// formatDate parses an ISO datetime and renders it as YYYY-MM-DD.
func formatDate(s string) string {
	t, err := time.Parse(time.RFC3339, s)
	if err != nil {
		return s
	}
	return t.Format("2006-01-02")
}